# Generated by Django 3.1.7 on 2022-11-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='用户名')),
                ('age', models.IntegerField(default=20, verbose_name='年龄')),
                ('idNumber', models.CharField(max_length=8, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=16, verbose_name='手机号')),
            ],
            options={
                'db_table': 'person',
            },
        ),
    ]
