# Generated by Django 3.1.7 on 2022-12-01 02:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=5, verbose_name='文件名')),
                ('add_time', models.DateTimeField(default=datetime.datetime(2022, 12, 1, 10, 0, 12, 814284), verbose_name='上传时间')),
            ],
            options={
                'db_table': 'file',
            },
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
