# Generated by Django 3.1.7 on 2022-12-01 02:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20221201_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simfiles',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 10, 12, 12, 857398), verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='simfiles',
            name='filename',
            field=models.CharField(max_length=100, verbose_name='文件名'),
        ),
    ]
